name: Terraform Workflow
on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  packages: write
  id-token: write
  contents: write

jobs:
  manage-infrastructure:
    runs-on: ubuntu-latest        
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_ACTOR,,}" >> ${GITHUB_ENV}

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -input=false -backend-config="key=${{ env.REPO }}-terraform.tfstate"

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate
    
      - name: Terraform Apply
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_project_name: ${{ env.REPO }}
        run: |
          cd terraform
          terraform apply -auto-approve -input=false